[package]
name = "qrcode-core"
version = "0.1.0"
edition = "2021"

[lib]
name = "qrcode_core"
path = "src/lib.rs"

[dependencies]
qrcode = "0.13"
image = "0.24"
thiserror = "1.0"
log = "0.4.27"
console_log = "1.0.0"
resvg = "0.36.0"
usvg = "0.36.0"
